apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mirai-uat

resources:
- deployment.yaml
- service.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: mirai-uat
    environment: uat
images:
- name: ghcr.io/sogos-llc/mirai-app/ai-service
  newName: ghcr.io/sogos-llc/mirai-app/ai-service
  newTag: uat-daa2445
