apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mirai-loc-dev

resources:
- deployment.yaml
- service.yaml
- ui-deployment.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: mirai-loc-dev
    environment: dev
