---
apiVersion: v1
kind: Namespace
metadata:
  name: mirai
  labels:
    app.kubernetes.io/name: mirai
    app.kubernetes.io/component: application
    environment: local
    tenant-isolation: enabled
