apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mirai-loc-dev

resources:
- deployment.yaml
- service.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: mirai-loc-dev
    environment: dev
images:
- name: ghcr.io/sogos-llc/mirai-app/ai-service
  newName: ghcr.io/sogos-llc/mirai-app/ai-service
  newTag: dev-a9d5971
