package service

import "context"

// AIProvider abstracts AI generation operations (Gemini, OpenAI, etc.).
type AIProvider interface {
	// GenerateCourseOutline generates a course outline from SME knowledge.
	GenerateCourseOutline(ctx context.Context, req GenerateOutlineRequest) (*GenerateOutlineResult, error)

	// GenerateLessonContent generates content for a single lesson.
	GenerateLessonContent(ctx context.Context, req GenerateLessonRequest) (*GenerateLessonResult, error)

	// RegenerateComponent regenerates a single component with modifications.
	RegenerateComponent(ctx context.Context, req RegenerateComponentRequest) (*RegenerateComponentResult, error)

	// ProcessSMEContent processes and distills knowledge from SME submission.
	ProcessSMEContent(ctx context.Context, req ProcessSMEContentRequest) (*ProcessSMEContentResult, error)

	// TestConnection tests if the API key is valid.
	TestConnection(ctx context.Context) error

	// ==========================================================================
	// Wizard AI Generation Methods (synchronous, fast operations)
	// ==========================================================================

	// GenerateImprovedTitle improves the course name and generates a description.
	GenerateImprovedTitle(ctx context.Context, courseName string) (*GenerateTitleResult, error)

	// GenerateCourseOutcomes generates desired course outcomes from a course name.
	// Used by the "magic wand" button in wizard step 1.
	// If RAG context is provided, it will be used to enhance the outcomes.
	GenerateCourseOutcomes(ctx context.Context, req GenerateOutcomesRequest) (*GenerateOutcomesResult, error)

	// GenerateSMEPersonas generates 3 diverse SME personas based on course topic.
	GenerateSMEPersonas(ctx context.Context, title, description string) (*GenerateSMEPersonasResult, error)

	// GenerateAudiencePersonas generates 3 diverse audience personas.
	GenerateAudiencePersonas(ctx context.Context, req GenerateAudiencePersonasRequest) (*GenerateAudiencePersonasResult, error)

	// GenerateToneOptions generates 3 tone/style options for the course.
	GenerateToneOptions(ctx context.Context, req GenerateToneOptionsRequest) (*GenerateToneOptionsResult, error)

	// GenerateImage generates an image from a text prompt.
	GenerateImage(ctx context.Context, req GenerateImageRequest) (*GenerateImageResult, error)

	// ==========================================================================
	// Knowledge-Grounded Planning Methods
	// ==========================================================================

	// AnalyzeDocument analyzes a single knowledge source document and produces
	// structured summaries, key facts, and search term suggestions per topic.
	AnalyzeDocument(ctx context.Context, req AnalyzeDocumentRequest) (*AnalyzeDocumentResult, error)

	// GenerateCoursePlan creates a structured course plan with sections and lessons,
	// each carrying targeted search terms for subsequent RAG retrieval.
	GenerateCoursePlan(ctx context.Context, req GenerateCoursePlanRequest) (*GenerateCoursePlanResult, error)
}

// =============================================================================
// Wizard AI Generation Types
// =============================================================================

// GenerateTitleResult contains the improved title and description.
type GenerateTitleResult struct {
	ImprovedTitle string
	Description   string
	TokensUsed    int64
}

// GenerateOutcomesRequest contains inputs for course outcome generation.
type GenerateOutcomesRequest struct {
	CourseName string
	RAGContext []RAGChunk // Optional RAG context from knowledge sources
}

// RAGChunk represents a chunk of content retrieved from the vector database.
type RAGChunk struct {
	SourceID       string
	SourceName     string
	Content        string
	RelevanceScore float32
}

// GenerateOutcomesResult contains AI-generated course outcomes.
type GenerateOutcomesResult struct {
	Outcomes   string // Freeform text with bullet points describing what learners will achieve
	Citations  []KnowledgeCitation
	TokensUsed int64
}

// KnowledgeCitation represents a reference to a knowledge source used in generation.
type KnowledgeCitation struct {
	SourceID       string
	SourceName     string
	Excerpt        string
	RelevanceScore float32
}

// WizardSMEPersona represents an SME persona generated by AI for the wizard.
type WizardSMEPersona struct {
	ID          string
	JobTitle    string
	Description string
	Skills      []string
	Voice       string
}

// GenerateSMEPersonasResult contains 3 diverse SME personas.
type GenerateSMEPersonasResult struct {
	Personas   []WizardSMEPersona
	TokensUsed int64
}

// WizardAudiencePersona represents an audience persona generated by AI.
type WizardAudiencePersona struct {
	ID          string
	Name        string
	Role        string
	Description string
	Goals       []string
}

// GenerateAudiencePersonasRequest contains context for audience generation.
type GenerateAudiencePersonasRequest struct {
	Title       string
	Description string
	SMEPersonas []WizardSMEPersona // Selected SME personas for context
}

// GenerateAudiencePersonasResult contains 3 diverse audience personas.
type GenerateAudiencePersonasResult struct {
	Personas   []WizardAudiencePersona
	TokensUsed int64
}

// WizardToneOption represents a tone option generated by AI.
type WizardToneOption struct {
	ID            string
	Name          string
	Description   string
	LevelOfDetail string // brief, moderate, comprehensive
}

// GenerateToneOptionsRequest contains context for tone generation.
type GenerateToneOptionsRequest struct {
	Title            string
	Description      string
	AudiencePersonas []WizardAudiencePersona // Selected audience personas for context
}

// GenerateToneOptionsResult contains 3 tone options.
type GenerateToneOptionsResult struct {
	Options    []WizardToneOption
	TokensUsed int64
}

// GenerateOutlineRequest contains inputs for outline generation.
type GenerateOutlineRequest struct {
	CourseTitle       string
	DesiredOutcome    string
	DesiredOutcomes   []string // Parsed individual learning outcomes for curriculum mapping
	SMEKnowledge      []SMEKnowledgeInput // Knowledge from selected SMEs
	TargetAudience    TargetAudienceInput // Target audience profile
	AdditionalContext string

	// Internal Data Only mode fields
	InternalDataOnly bool                   // When true, use only RAG content
	DocumentIndices  []DocumentIndexInput   // Structured indices of uploaded documents
	RAGContext       []RAGChunkInput        // Retrieved chunks from knowledge sources

	// Constraints derived from knowledge scope (when available)
	Constraints *CourseConstraintsInput // Hard bounds AI must respect

	// Approved course plan for guided outline generation
	CoursePlan *CoursePlanContext // When set, outline follows plan structure
}

// CourseConstraintsInput provides deterministic bounds for outline generation.
// When provided, the AI MUST generate within these constraints.
type CourseConstraintsInput struct {
	MinSections          int
	MaxSections          int
	MinLessonsPerSection int
	MaxLessonsPerSection int
	MinTotalLessons      int
	MaxTotalLessons      int
	RecommendedDepth     string // "basic", "intermediate", "advanced"
}

// DocumentIndexInput represents a document's structured index for AI navigation.
type DocumentIndexInput struct {
	SourceID             string   // Knowledge source ID
	SourceName           string   // Document name
	Title                string   // Document title
	MainTopics           []string // Major sections/topics
	KeyConcepts          []string // Important terms and concepts
	EstimatedLessonCount int      // How many lessons this content could support
	ContentDepth         string   // "basic", "intermediate", "advanced"
}

// RAGChunkInput represents a retrieved knowledge chunk for content generation.
type RAGChunkInput struct {
	ChunkID         string  // Unique chunk identifier for provenance tracking
	SourceID        string  // Knowledge source ID for citation
	SourceName      string  // Document name for citation
	Content         string  // The actual chunk content
	ChunkIndex      int     // Position in original document
	SimilarityScore float32 // Relevance score from vector search
	Scope           string  // Source scope: "course", "team", or "global"
}

// SMEKnowledgeInput represents knowledge from an SME.
type SMEKnowledgeInput struct {
	SMEName  string
	Domain   string
	Summary  string
	Chunks   []string // Knowledge chunks
	Keywords []string // Combined keywords
}

// TargetAudienceInput represents the target audience profile.
type TargetAudienceInput struct {
	Role              string
	ExperienceLevel   string
	LearningGoals     []string
	Prerequisites     []string
	Challenges        []string
	Motivations       []string
	IndustryContext   string
	TypicalBackground string
}

// GenerateOutlineResult contains the generated outline.
type GenerateOutlineResult struct {
	Sections   []OutlineSectionResult
	TokensUsed int64
}

// OutlineSectionResult represents a generated section.
type OutlineSectionResult struct {
	Title          string
	Description    string
	Order          int
	Lessons        []OutlineLessonResult
	IsFirstSection bool // First section in course
	IsLastSection  bool // Last section in course

	// Section metadata for curriculum planning
	Level                string   // Learning level: "introduce", "develop", "master"
	Intent               string   // Primary intent: "teach", "assess", "reinforce"
	Emphasis             string   // Relative importance: "low", "medium", "high"
	MappedOutcomeIndices []int    // Indices of course outcomes this section addresses
	GroundingScore       float32  // How grounded in knowledge sources (0.0-1.0)
	ContributingChunkIDs []string // IDs of RAG chunks that informed this section
}

// OutlineLessonResult represents a generated lesson in the outline.
type OutlineLessonResult struct {
	Title                    string
	Description              string
	Order                    int
	EstimatedDurationMinutes int
	LearningObjectives       []string
	IsFirstInSection         bool // First lesson in section
	IsLastInSection          bool // Last lesson in section
	IsFirstInCourse          bool // First lesson in entire course
	IsLastInCourse           bool // Last lesson in entire course

	// Grounding (inherited from section at outline time, refined during lesson generation)
	GroundingScore float32 // How grounded in knowledge sources (0.0-1.0)
}

// GenerateLessonRequest contains inputs for lesson content generation.
type GenerateLessonRequest struct {
	// Course context
	CourseTitle       string
	CourseDescription string
	CourseOutline     []OutlineSectionSummary // Full outline for context

	// Section context
	SectionTitle       string
	SectionDescription string
	SectionOrder       int
	IsFirstSection     bool
	IsLastSection      bool

	// Lesson context
	LessonTitle        string
	LessonDescription  string
	LessonOrder        int // Order within section
	LearningObjectives []string

	// Position flags
	IsFirstInSection bool // First lesson in this section
	IsLastInSection  bool // Last lesson in this section
	IsFirstInCourse  bool // First lesson in entire course
	IsLastInCourse   bool // Last lesson in entire course

	// Navigation context for segues
	PreviousLessonTitle   string // Previous lesson title
	PreviousLessonSummary string // Summary of previous lesson content
	NextLessonTitle       string // Next lesson title
	NextSectionTitle      string // Next section title (for section transitions)

	// Previously generated content in this section (for context building)
	PreviousLessonsInSection []GeneratedLessonSummary

	// Knowledge inputs
	SMEKnowledge   []SMEKnowledgeInput
	TargetAudience TargetAudienceInput

	// Additional user context for content generation
	AdditionalContext string

	// Internal Data Only mode fields
	InternalDataOnly bool            // When true, use only RAG content
	RAGContext       []RAGChunkInput // Retrieved chunks from knowledge sources
}

// OutlineSectionSummary provides outline context for lesson generation.
type OutlineSectionSummary struct {
	Title       string
	Description string
	Order       int
	LessonCount int
	Lessons     []OutlineLessonSummary
}

// OutlineLessonSummary provides lesson info within outline context.
type OutlineLessonSummary struct {
	Title              string
	Description        string
	Order              int
	LearningObjectives []string
}

// GeneratedLessonSummary provides summary of previously generated content.
type GeneratedLessonSummary struct {
	Title          string
	ComponentCount int
	KeyPoints      []string // Main points covered (extracted from text components)
	SegueText      string   // How this lesson transitioned to the next
}

// GenerateLessonResult contains the generated lesson content.
type GenerateLessonResult struct {
	Components []LessonComponentResult
	SegueText  string // Transition to next lesson
	TokensUsed int64
}

// LessonComponentResult represents a generated component.
type LessonComponentResult struct {
	Type        string // text, heading, image, quiz
	Order       int
	ContentJSON string // JSON-encoded content based on type
}

// RegenerateComponentRequest contains inputs for component regeneration.
type RegenerateComponentRequest struct {
	ComponentType      string
	CurrentContentJSON string
	ModificationPrompt string
	LessonContext      string
	TargetAudience     TargetAudienceInput
}

// RegenerateComponentResult contains the regenerated component.
type RegenerateComponentResult struct {
	ContentJSON string
	TokensUsed  int64
}

// ProcessSMEContentRequest contains inputs for SME content processing.
type ProcessSMEContentRequest struct {
	SMEName       string
	SMEDomain     string
	ExtractedText string // Raw text from uploaded document
}

// ProcessSMEContentResult contains the processed SME knowledge.
type ProcessSMEContentResult struct {
	Summary    string
	Chunks     []SMEChunkResult
	TokensUsed int64
}

// SMEChunkResult represents a distilled knowledge chunk.
type SMEChunkResult struct {
	Content        string
	Topic          string
	Keywords       []string
	RelevanceScore float32
}

// =============================================================================
// Knowledge-Grounded Planning Types
// =============================================================================

// AnalyzeDocumentRequest contains inputs for document analysis.
type AnalyzeDocumentRequest struct {
	SourceID       string
	SourceName     string
	DocumentText   string
	CourseTitle    string
	DesiredOutcome string
}

// AnalyzeDocumentResult contains the structured analysis of a single document.
type AnalyzeDocumentResult struct {
	Summary      string
	MainTopics   []string
	KeyFacts     []string
	ContentDepth string // "basic", "intermediate", "advanced"
	SectionHints []SectionHintResult
	TokensUsed   int64
}

// SectionHintResult is a suggested section derived from document analysis.
type SectionHintResult struct {
	TopicName   string
	SearchTerms []string
	KeyPoints   []string
}

// CoursePlanContext provides the approved plan structure for guided outline generation.
type CoursePlanContext struct {
	Sections []PlannedSectionContext
}

// PlannedSectionContext provides plan context for a single section.
type PlannedSectionContext struct {
	Title       string
	Description string
	SourceIDs   []string
	Rationale   string
	Lessons     []PlannedLessonContext
}

// PlannedLessonContext provides plan context for a single lesson.
type PlannedLessonContext struct {
	Title         string
	Description   string
	LearningGoals []string
}

// GenerateCoursePlanRequest contains inputs for course plan generation.
type GenerateCoursePlanRequest struct {
	CourseTitle       string
	DesiredOutcome    string
	DocumentAnalyses []AnalyzeDocumentResult
	SMEKnowledge     []SMEKnowledgeInput
	TargetAudience   TargetAudienceInput
	AdditionalContext string
	InternalDataOnly bool
	Constraints      *CourseConstraintsInput
}

// GenerateCoursePlanResult contains the generated course plan.
type GenerateCoursePlanResult struct {
	Sections   []PlannedSectionResult
	TokensUsed int64
}

// PlannedSectionResult is a planned course section with targeted search terms.
type PlannedSectionResult struct {
	Title       string
	Description string
	SearchTerms []string
	SourceIDs   []string
	Lessons     []PlannedLessonResult
	Rationale   string
}

// PlannedLessonResult is a planned lesson with its own search terms.
type PlannedLessonResult struct {
	Title         string
	Description   string
	SearchTerms   []string
	LearningGoals []string
}

// =============================================================================
// Image Generation Types
// =============================================================================

// GenerateImageRequest contains inputs for image generation.
type GenerateImageRequest struct {
	Prompt      string // Image description/prompt
	AspectRatio string // e.g., "16:9", "1:1", "4:3" - defaults to "16:9"
}

// GenerateImageResult contains the generated image.
type GenerateImageResult struct {
	ImageData  []byte // Raw image bytes (PNG format)
	MimeType   string // MIME type of the image
	TokensUsed int64
}
