import { Page, expect } from '@playwright/test';
import { takeScreenshot, waitForAIGeneration } from '../helpers';

/**
 * Page Object for the Course Creation Wizard.
 *
 * The wizard has 7 steps:
 * 1. Course Name - Enter initial topic
 * 2. Title & Description - Review AI-generated title
 * 3. SME Personas - Select subject matter experts
 * 4. Target Audience - Select audience personas
 * 5. Tone & Style - Select communication style
 * 6. Additional Context - Add extra instructions (no AI)
 * 7. Generate Outline - Triggers background job
 */
export class WizardPage {
  private stepScreenshotCount = 0;

  constructor(private page: Page) {}

  /** Navigate to the course wizard */
  async goto(): Promise<void> {
    await this.page.goto('/course/wizard', { waitUntil: 'domcontentloaded' });
    await this.page.waitForTimeout(2000);
    await this.screenshot('wizard-start', 'Course wizard loaded');
  }

  /** Get the current step name from the progress indicator */
  async getCurrentStep(): Promise<string> {
    // The wizard shows step indicators at the top
    const activeStep = this.page.locator('[class*="active"], [aria-current="step"]');
    return (await activeStep.textContent()) || 'unknown';
  }

  // ===== STEP 1: Course Name =====

  /** Fill in the course name/topic */
  async enterCourseName(name: string): Promise<void> {
    console.log('\n--- Wizard Step 1: Course Name ---');
    const input = this.page.locator('input').first();
    await expect(input).toBeVisible({ timeout: 10000 });
    await input.fill(name);
    await this.screenshot('step1-name-entered', 'Course name entered');
  }

  /** Click the "Generate Title" button and wait for AI */
  async clickGenerateTitle(): Promise<void> {
    const btn = this.page.getByRole('button', { name: /generate title/i });
    await expect(btn).toBeVisible({ timeout: 5000 });
    console.log('Clicking Generate Title...');
    await btn.click();
    await waitForAIGeneration(this.page, 'title generation');
    await this.screenshot('step2-title-generated', 'Title generated by AI');
  }

  // ===== STEP 2: Title & Description =====

  /** Click "Generate Personas" to proceed to SME step and wait for AI */
  async clickGeneratePersonas(): Promise<void> {
    console.log('\n--- Wizard Step 2: Review Title → Generate Personas ---');
    const btn = this.page.getByRole('button', { name: /generate personas/i });
    await expect(btn).toBeVisible({ timeout: 10000 });
    await expect(btn).toBeEnabled({ timeout: 10000 });
    console.log('Clicking Generate Personas...');
    await btn.click();
    await waitForAIGeneration(this.page, 'SME personas');
    await this.screenshot('step3-sme', 'SME Personas step');
  }

  // ===== STEP 3: SME Personas =====

  /** Click "Generate Audiences" to proceed to audience step and wait for AI */
  async clickGenerateAudiences(): Promise<void> {
    console.log('\n--- Wizard Step 3: SME Personas → Generate Audiences ---');
    const btn = this.page.getByRole('button', { name: /generate audiences/i });
    await expect(btn).toBeVisible({ timeout: 10000 });
    await expect(btn).toBeEnabled({ timeout: 10000 });
    console.log('Clicking Generate Audiences...');
    await btn.click();
    await waitForAIGeneration(this.page, 'audience personas');
    await this.screenshot('step4-audience', 'Audience step');
  }

  // ===== STEP 4: Target Audience =====

  /** Click "Generate Tones" to proceed to tone step and wait for AI */
  async clickGenerateTones(): Promise<void> {
    console.log('\n--- Wizard Step 4: Target Audience → Generate Tones ---');
    const btn = this.page.getByRole('button', { name: /generate tones/i });
    await expect(btn).toBeVisible({ timeout: 10000 });
    await expect(btn).toBeEnabled({ timeout: 10000 });
    console.log('Clicking Generate Tones...');
    await btn.click();
    await waitForAIGeneration(this.page, 'tone options');
    await this.screenshot('step5-tone', 'Tone & Style step');
  }

  // ===== STEP 5: Tone & Style =====

  /** Click "Add Context" to proceed to context step (no AI call) */
  async clickAddContext(): Promise<void> {
    console.log('\n--- Wizard Step 5: Tone & Style → Add Context ---');
    const btn = this.page.getByRole('button', { name: /add context/i });
    await expect(btn).toBeVisible({ timeout: 10000 });
    await expect(btn).toBeEnabled({ timeout: 10000 });
    console.log('Clicking Add Context...');
    await btn.click();
    await this.page.waitForTimeout(2000);
    await this.screenshot('step6-context', 'Additional Context step');
  }

  // ===== STEP 6: Additional Context =====

  /** Add additional context and click "Generate Outline" */
  async handleContextStep(context?: string): Promise<void> {
    console.log('\n--- Wizard Step 6: Additional Context ---');

    if (context) {
      const textarea = this.page.locator('textarea').first();
      if ((await textarea.count()) > 0 && (await textarea.isVisible())) {
        await textarea.fill(context);
        await this.screenshot('context-filled', 'Context entered');
      }
    }

    // Click "Generate Outline" (prefer this over "Skip & Generate")
    const generateBtn = this.page.getByRole('button', { name: 'Generate Outline' });
    await expect(generateBtn).toBeVisible({ timeout: 10000 });
    await expect(generateBtn).toBeEnabled({ timeout: 10000 });
    console.log('Clicking Generate Outline...');
    await generateBtn.click();
  }

  // ===== STEP 7: Success Modal (after background job is queued) =====

  /**
   * Wait for success modal to appear.
   * Note: The modal appears immediately after the job is QUEUED (not completed).
   * The actual outline generation happens in the background.
   */
  async waitForSuccessModal(): Promise<void> {
    console.log('\n--- Wizard Step 7: Waiting for Success Modal ---');
    // Wait for the success modal which says "Outline Generation Started!"
    await this.page.getByText(/outline generation started/i).waitFor({
      state: 'visible',
      timeout: 60000,
    });
    await this.screenshot('success-modal', 'Outline generation queued');
  }

  /** Click "Got it!" to dismiss modal and redirect to dashboard */
  async dismissSuccessModal(): Promise<boolean> {
    console.log('Dismissing success modal...');

    try {
      const gotItBtn = this.page.getByRole('button', { name: /got it/i });
      await gotItBtn.waitFor({ state: 'visible', timeout: 10000 });
      console.log('Clicking "Got it!" button...');
      await gotItBtn.click();

      // Wait for redirect to dashboard
      await this.page.waitForURL(/\/dashboard/, { timeout: 10000 });
      console.log('Redirected to dashboard');
      await this.screenshot('dashboard', 'Redirected to dashboard');
      return true;
    } catch (error) {
      console.log('Failed to dismiss modal:', error);
      await this.screenshot('dismiss-failed', 'Failed to dismiss modal');
      return false;
    }
  }

  // ===== Complete Flow =====

  /**
   * Run the complete wizard flow from start to finish.
   *
   * Flow:
   * 1. Enter course name → Click "Generate Title" (AI: ~20s)
   * 2. Review title → Click "Generate Personas" (AI: ~20s)
   * 3. Review SMEs → Click "Generate Audiences" (AI: ~20s)
   * 4. Review audiences → Click "Generate Tones" (AI: ~20s)
   * 5. Review tones → Click "Add Context" (no AI)
   * 6. Enter context → Click "Generate Outline" (queues background job)
   * 7. Success modal appears → Click "Got it!" → Redirect to dashboard
   *
   * Note: The course won't appear in content library immediately.
   * The outline generation is a background job that takes ~1-2 minutes.
   *
   * Returns true if wizard completed (job queued) successfully.
   */
  async completeWizard(options: {
    courseName: string;
    additionalContext?: string;
  }): Promise<boolean> {
    const { courseName, additionalContext } = options;

    // Step 1: Course Name
    await this.enterCourseName(courseName);
    await this.clickGenerateTitle();

    // Step 2: Title & Description → Generate Personas
    await this.clickGeneratePersonas();

    // Step 3: SME Personas → Generate Audiences
    await this.clickGenerateAudiences();

    // Step 4: Target Audience → Generate Tones
    await this.clickGenerateTones();

    // Step 5: Tone & Style → Add Context
    await this.clickAddContext();

    // Step 6: Additional Context → Generate Outline
    await this.handleContextStep(additionalContext);

    // Step 7: Success Modal
    await this.waitForSuccessModal();
    return this.dismissSuccessModal();
  }

  // ===== Utilities =====

  /** Take a screenshot with auto-incrementing prefix */
  private async screenshot(name: string, description?: string): Promise<void> {
    this.stepScreenshotCount++;
    const prefix = String(this.stepScreenshotCount).padStart(2, '0');
    await takeScreenshot(this.page, `wizard-${prefix}-${name}`, description);
  }
}
