import { Page, expect } from '@playwright/test';
import { takeScreenshot, waitForAIGeneration } from '../helpers';

/**
 * Page Object for the Course Creation Wizard.
 *
 * The wizard has 7 steps:
 * 1. Course Name - Enter initial topic
 * 2. Title & Description - Review AI-generated title
 * 3. SME Personas - Select subject matter experts
 * 4. Target Audience - Select audience personas
 * 5. Knowledge Sources - Upload documents (optional)
 * 6. Tone & Style - Select communication style + Additional Context
 * 7. Generate Outline - Triggers background job
 */
export class WizardPage {
  private stepScreenshotCount = 0;

  constructor(private page: Page) {}

  /** Navigate to the course wizard */
  async goto(): Promise<void> {
    await this.page.goto('/course/wizard', { waitUntil: 'domcontentloaded' });
    await this.page.waitForTimeout(2000);
    await this.screenshot('wizard-start', 'Course wizard loaded');
  }

  /** Get the current step name from the progress indicator */
  async getCurrentStep(): Promise<string> {
    // The wizard shows step indicators at the top
    const activeStep = this.page.locator('[class*="active"], [aria-current="step"]');
    return (await activeStep.textContent()) || 'unknown';
  }

  // ===== STEP 1: Course Name =====

  /** Fill in the course name/topic */
  async enterCourseName(name: string): Promise<void> {
    console.log('\n--- Wizard Step 1: Course Name ---');
    const input = this.page.locator('input').first();
    await expect(input).toBeVisible({ timeout: 10000 });
    await input.fill(name);
    await this.screenshot('step1-name-entered', 'Course name entered');
  }

  /** Click the "Generate Title" button and wait for AI */
  async clickGenerateTitle(): Promise<void> {
    const btn = this.page.getByRole('button', { name: /generate title/i });
    await expect(btn).toBeVisible({ timeout: 5000 });
    console.log('Clicking Generate Title...');
    await btn.click();
    await waitForAIGeneration(this.page, 'title generation');
    await this.screenshot('step2-title-generated', 'Title generated by AI');
  }

  // ===== STEP 2: Title & Description =====

  /** Click "Generate Personas" to proceed to SME step and wait for AI */
  async clickGeneratePersonas(): Promise<void> {
    console.log('\n--- Wizard Step 2: Review Title → Generate Personas ---');
    const btn = this.page.getByRole('button', { name: /generate personas/i });
    await expect(btn).toBeVisible({ timeout: 10000 });
    await expect(btn).toBeEnabled({ timeout: 10000 });
    console.log('Clicking Generate Personas...');
    await btn.click();
    await waitForAIGeneration(this.page, 'SME personas');
    await this.screenshot('step3-sme', 'SME Personas step');
  }

  // ===== STEP 3: SME Personas =====

  /** Click "Generate Audiences" to proceed to audience step and wait for AI */
  async clickGenerateAudiences(): Promise<void> {
    console.log('\n--- Wizard Step 3: SME Personas → Generate Audiences ---');
    const btn = this.page.getByRole('button', { name: /generate audiences/i });
    await expect(btn).toBeVisible({ timeout: 10000 });
    await expect(btn).toBeEnabled({ timeout: 10000 });
    console.log('Clicking Generate Audiences...');
    await btn.click();
    await waitForAIGeneration(this.page, 'audience personas');
    await this.screenshot('step4-audience', 'Audience step');
  }

  // ===== STEP 4: Target Audience =====

  /** Click "Continue" or "Skip" to proceed to knowledge sources step */
  async clickContinueToKnowledgeSources(): Promise<void> {
    console.log('\n--- Wizard Step 4: Target Audience → Knowledge Sources ---');
    // The button says "Generate Tones" but now goes to Knowledge Sources first
    const btn = this.page.getByRole('button', { name: /generate audiences|continue/i }).last();
    await expect(btn).toBeVisible({ timeout: 10000 });
    await expect(btn).toBeEnabled({ timeout: 10000 });
    console.log('Clicking to proceed to Knowledge Sources...');
    await btn.click();
    await this.page.waitForTimeout(2000);
    await this.screenshot('step5-knowledge-sources', 'Knowledge Sources step');
  }

  // ===== STEP 5: Knowledge Sources =====

  /**
   * Handle the knowledge sources step.
   * This step is optional - can upload files or skip.
   * @param files - Optional array of file paths to upload
   */
  async handleKnowledgeSourcesStep(files?: string[]): Promise<void> {
    console.log('\n--- Wizard Step 5: Knowledge Sources ---');

    // If files provided, upload them
    if (files && files.length > 0) {
      const fileInput = this.page.locator('input[type="file"]');
      if (await fileInput.count() > 0) {
        await fileInput.setInputFiles(files);
        await this.page.waitForTimeout(1000);
        await this.screenshot('files-uploaded', 'Files uploaded');
      }
    }

    // Click Continue or Skip to proceed (button label changes based on files)
    const continueBtn = this.page.getByRole('button', { name: /continue|skip/i }).last();
    await expect(continueBtn).toBeVisible({ timeout: 10000 });
    console.log('Clicking to proceed from Knowledge Sources...');
    await continueBtn.click();

    // Wait for tone generation
    await waitForAIGeneration(this.page, 'tone options');
    await this.screenshot('step6-tone', 'Tone & Style step');
  }

  // ===== STEP 6: Tone & Style + Additional Context (Combined) =====
  // Note: The wizard UI was updated to combine Tone and Context into one step.
  // The "Generate Outline" button is now on the Tone step.

  /** Add additional context (optional) and click "Generate Outline" */
  async handleToneAndContextStep(context?: string): Promise<void> {
    console.log('\n--- Wizard Step 5: Tone & Style + Additional Context ---');

    // Fill in additional context if provided (textarea is on the same page as tone selection)
    if (context) {
      const textarea = this.page.locator('textarea').first();
      if ((await textarea.count()) > 0 && (await textarea.isVisible())) {
        await textarea.fill(context);
        await this.screenshot('context-filled', 'Context entered');
      }
    }

    // Click "Generate Outline" to proceed
    const generateBtn = this.page.getByRole('button', { name: 'Generate Outline' });
    await expect(generateBtn).toBeVisible({ timeout: 10000 });
    await expect(generateBtn).toBeEnabled({ timeout: 10000 });
    console.log('Clicking Generate Outline...');
    await generateBtn.click();
  }

  // ===== STEP 6: Wait for Outline Generation =====
  // Note: The wizard now navigates directly to the outline page, no success modal.

  /**
   * Wait for outline generation to complete.
   * The wizard navigates to /course/{id}/outline which shows:
   * 1. "Loading outline..." (initial)
   * 2. "Creating your outline..." with "Wait for outline" button
   * 3. "Review Your Course Outline" (complete)
   */
  async waitForOutlineGeneration(): Promise<string> {
    console.log('\n--- Wizard Step 6: Waiting for Outline Generation ---');

    // Wait for URL to change to outline page
    await this.page.waitForURL(/\/course\/[^/]+\/outline/, { timeout: 30000 });
    console.log('Navigated to outline page');

    // Extract course ID from URL
    const url = this.page.url();
    const match = url.match(/\/course\/([^/]+)\/outline/);
    const courseId = match ? match[1] : '';
    console.log(`Course ID: ${courseId}`);

    // Wait for page to stabilize (pass "Loading outline..." state)
    await this.page.waitForTimeout(3000);
    await this.screenshot('outline-page', 'Outline page');

    // Wait for "Wait for outline" button to appear and click it
    const waitButton = this.page.getByRole('button', { name: /wait for outline/i });
    console.log('Looking for "Wait for outline" button...');

    try {
      await waitButton.waitFor({ state: 'visible', timeout: 30000 });
      console.log('Found "Wait for outline" button, clicking...');
      await waitButton.click();
      await this.screenshot('clicked-wait', 'Clicked Wait for outline');
    } catch {
      console.log('Wait button not found - outline may already be ready or loading');
    }

    // Now wait for outline to complete (up to 5 minutes)
    const reviewHeading = this.page.getByText(/Review Your Course Outline/i);
    console.log('Waiting for outline to complete (up to 5 minutes)...');

    for (let attempt = 0; attempt < 60; attempt++) {
      const outlineReady = await reviewHeading.isVisible().catch(() => false);
      if (outlineReady) {
        console.log(`Outline ready after ${(attempt + 1) * 5}s`);
        await this.screenshot('outline-ready', 'Outline complete');
        return courseId;
      }

      if (attempt % 12 === 0) {
        console.log(`Poll ${attempt + 1}/60: Still waiting...`);
      }
      await this.page.waitForTimeout(5000);
    }

    console.log('Timeout waiting for outline - continuing anyway');
    await this.screenshot('outline-timeout', 'Outline timeout');
    return courseId;
  }

  // ===== Complete Flow =====

  /**
   * Run the complete wizard flow from start to finish.
   *
   * Flow (Updated - Now includes Knowledge Sources step):
   * 1. Enter course name → Click "Generate Title" (AI: ~20s)
   * 2. Review title → Click "Generate Personas" (AI: ~20s)
   * 3. Review SMEs → Click "Generate Audiences" (AI: ~20s)
   * 4. Review audiences → Proceed to Knowledge Sources
   * 5. Knowledge Sources → Skip or upload files → Generate Tones (AI: ~20s)
   * 6. Review tones + Enter context → Click "Generate Outline"
   * 7. Redirect to outline page → Wait for outline generation
   *
   * Returns the course ID on success, or empty string on failure.
   */
  async completeWizard(options: {
    courseName: string;
    additionalContext?: string;
    knowledgeSourceFiles?: string[];
  }): Promise<string> {
    const { courseName, additionalContext, knowledgeSourceFiles } = options;

    // Step 1: Course Name
    await this.enterCourseName(courseName);
    await this.clickGenerateTitle();

    // Step 2: Title & Description → Generate Personas
    await this.clickGeneratePersonas();

    // Step 3: SME Personas → Generate Audiences
    await this.clickGenerateAudiences();

    // Step 4: Target Audience → Knowledge Sources
    await this.clickContinueToKnowledgeSources();

    // Step 5: Knowledge Sources → Generate Tones
    await this.handleKnowledgeSourcesStep(knowledgeSourceFiles);

    // Step 6: Tone & Style + Additional Context → Generate Outline
    await this.handleToneAndContextStep(additionalContext);

    // Step 7: Wait for Outline Generation
    return this.waitForOutlineGeneration();
  }

  // ===== Utilities =====

  /** Take a screenshot with auto-incrementing prefix */
  private async screenshot(name: string, description?: string): Promise<void> {
    this.stepScreenshotCount++;
    const prefix = String(this.stepScreenshotCount).padStart(2, '0');
    await takeScreenshot(this.page, `wizard-${prefix}-${name}`, description);
  }
}
