-- Force RLS to apply even for table owners (the mirai app user)
-- This ensures tenant isolation is enforced regardless of table ownership

ALTER TABLE companies FORCE ROW LEVEL SECURITY;
ALTER TABLE course_generation_inputs FORCE ROW LEVEL SECURITY;
ALTER TABLE course_modules FORCE ROW LEVEL SECURITY;
ALTER TABLE course_outlines FORCE ROW LEVEL SECURITY;
ALTER TABLE courses FORCE ROW LEVEL SECURITY;
ALTER TABLE folders FORCE ROW LEVEL SECURITY;
ALTER TABLE generated_lessons FORCE ROW LEVEL SECURITY;
ALTER TABLE generation_jobs FORCE ROW LEVEL SECURITY;
ALTER TABLE invitations FORCE ROW LEVEL SECURITY;
ALTER TABLE lesson_components FORCE ROW LEVEL SECURITY;
ALTER TABLE lessons FORCE ROW LEVEL SECURITY;
ALTER TABLE notifications FORCE ROW LEVEL SECURITY;
ALTER TABLE outline_lessons FORCE ROW LEVEL SECURITY;
ALTER TABLE outline_sections FORCE ROW LEVEL SECURITY;
ALTER TABLE pending_registrations FORCE ROW LEVEL SECURITY;
ALTER TABLE scorm_packages FORCE ROW LEVEL SECURITY;
ALTER TABLE sme_knowledge_chunks FORCE ROW LEVEL SECURITY;
ALTER TABLE sme_task_submissions FORCE ROW LEVEL SECURITY;
ALTER TABLE sme_tasks FORCE ROW LEVEL SECURITY;
ALTER TABLE sme_team_access FORCE ROW LEVEL SECURITY;
ALTER TABLE subject_matter_experts FORCE ROW LEVEL SECURITY;
ALTER TABLE target_audience_templates FORCE ROW LEVEL SECURITY;
ALTER TABLE team_members FORCE ROW LEVEL SECURITY;
ALTER TABLE teams FORCE ROW LEVEL SECURITY;
ALTER TABLE tenant_ai_settings FORCE ROW LEVEL SECURITY;
ALTER TABLE tenants FORCE ROW LEVEL SECURITY;
ALTER TABLE users FORCE ROW LEVEL SECURITY;
