apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mirai-uat

resources:
- deployment.yaml
- service.yaml
- pvc.yaml

labels:
- pairs:
    environment: uat
    app.kubernetes.io/part-of: mirai-uat
