import type { DriveStep } from 'driver.js';

export const dashboardTourSteps: DriveStep[] = [
  {
    element: '[data-tour="dashboard-hero"]',
    popover: {
      title: 'Welcome to Mirai',
      description:
        'This is your home base. From here you can create new courses and manage existing ones.',
      side: 'bottom',
      align: 'center',
    },
  },
  {
    element: '[data-tour="dashboard-create-btn"]',
    popover: {
      title: 'Create a Course',
      description:
        'Click here to launch the AI-powered course wizard. It will guide you step by step.',
      side: 'left',
      align: 'center',
    },
  },
  {
    element: '[data-tour="dashboard-courses"]',
    popover: {
      title: 'Your Courses',
      description:
        'All your courses appear here. Switch between Recent and In Progress to track active generations.',
      side: 'top',
      align: 'center',
    },
  },
  {
    element: '[data-tour="dashboard-tabs"]',
    popover: {
      title: 'Recent & In Progress',
      description:
        'Use these tabs to see finished courses or ones still being generated by the AI.',
      side: 'bottom',
      align: 'center',
    },
  },
];
