apiVersion: v1
kind: Service
metadata:
  name: temporal-server
  namespace: mirai-uat
  labels:
    app: temporal-server
    environment: uat
spec:
  type: ClusterIP
  ports:
  - port: 7233
    targetPort: 7233
    name: grpc
  selector:
    app: temporal-server
