apiVersion: v1
kind: Service
metadata:
  name: temporal
  namespace: mirai-uat
  labels:
    app: temporal
    environment: uat
spec:
  type: ClusterIP
  ports:
  - port: 7233
    targetPort: 7233
    name: grpc
  selector:
    app: temporal
