"""Course outline models - structured output from outline generation."""

from pydantic import BaseModel, Field


class LearningObjective(BaseModel):
    """A measurable learning objective for a lesson."""

    description: str = Field(description="Clear, measurable learning objective")
    bloom_level: str = Field(
        default="understand",
        description="Bloom's taxonomy level: remember, understand, apply, analyze, evaluate, create",
    )


class OutlineLesson(BaseModel):
    """A lesson within a course section."""

    id: str = Field(description="Unique lesson identifier (e.g. 'lesson-1-1')")
    title: str = Field(description="Lesson title")
    description: str = Field(description="Brief lesson description")
    learning_objectives: list[LearningObjective] = Field(
        default_factory=list, description="Measurable learning objectives"
    )
    estimated_duration_minutes: int = Field(
        default=15, description="Estimated duration in minutes"
    )
    key_topics: list[str] = Field(
        default_factory=list, description="Key topics covered"
    )


class OutlineSection(BaseModel):
    """A section (module) within a course outline."""

    id: str = Field(description="Unique section identifier (e.g. 'section-1')")
    title: str = Field(description="Section title")
    description: str = Field(description="Section description and rationale")
    lessons: list[OutlineLesson] = Field(description="Lessons in this section")
    order: int = Field(description="Section order (1-based)")


class CourseOutline(BaseModel):
    """Complete course outline generated by AI."""

    title: str = Field(description="Course title")
    description: str = Field(description="Course description")
    target_audience: str = Field(default="", description="Target audience description")
    sections: list[OutlineSection] = Field(description="Course sections")
    estimated_total_duration_minutes: int = Field(
        default=0, description="Total estimated duration"
    )
    prerequisite_knowledge: list[str] = Field(
        default_factory=list, description="Prerequisites"
    )
