"""Course outline models - structured output from outline generation."""

from __future__ import annotations

from pydantic import BaseModel, Field

from src.models.lesson import LessonContent


class LearningObjective(BaseModel):
    """A measurable learning objective for a lesson."""

    description: str = Field(description="Clear, measurable learning objective")
    bloom_level: str = Field(
        default="understand",
        description="Bloom's taxonomy level: remember, understand, apply, analyze, evaluate, create",
    )


class OutlineLesson(BaseModel):
    """A lesson within a course section."""

    id: str = Field(description="Unique lesson identifier (e.g. 'lesson-1-1')")
    title: str = Field(description="Lesson title")
    description: str = Field(description="Brief lesson description")
    learning_objectives: list[LearningObjective] = Field(
        default_factory=list, description="Measurable learning objectives"
    )
    estimated_duration_minutes: int = Field(
        default=15, description="Estimated duration in minutes"
    )
    key_topics: list[str] = Field(
        default_factory=list, description="Key topics covered"
    )
    content: LessonContent | None = Field(
        default=None, description="Populated during lesson generation phase"
    )


class ConceptNode(BaseModel):
    """A concept tracked across the course for progression mapping."""

    concept: str = Field(description="Name of the concept")
    first_taught_in: str = Field(description="Lesson ID where concept is first introduced")
    reinforced_in: list[str] = Field(
        default_factory=list, description="Lesson IDs where concept is reinforced"
    )
    prerequisites: list[str] = Field(
        default_factory=list, description="Concept names that must be learned first"
    )


class ConceptMap(BaseModel):
    """Cross-lesson concept progression map for the course."""

    concepts: list[ConceptNode] = Field(
        default_factory=list, description="All concepts tracked across the course"
    )


class OutlineSection(BaseModel):
    """A section (module) within a course outline."""

    id: str = Field(description="Unique section identifier (e.g. 'section-1')")
    title: str = Field(description="Section title")
    description: str = Field(description="Section description and rationale")
    lessons: list[OutlineLesson] = Field(description="Lessons in this section")
    order: int = Field(description="Section order (1-based)")
    introduction: str = Field(default="", description="Section introduction text")
    summary: str = Field(default="", description="Section summary text")


class CourseOutline(BaseModel):
    """Complete course outline generated by AI."""

    title: str = Field(description="Course title")
    description: str = Field(description="Course description")
    target_audience: str = Field(default="", description="Target audience description")
    sections: list[OutlineSection] = Field(description="Course sections")
    estimated_total_duration_minutes: int = Field(
        default=0, description="Total estimated duration"
    )
    prerequisite_knowledge: list[str] = Field(
        default_factory=list, description="Prerequisites"
    )
    concept_map: ConceptMap | None = Field(
        default=None, description="Cross-lesson concept progression map"
    )
    conclusion: str = Field(default="", description="Course conclusion text")
