"""Wizard output models for course creation wizard steps."""

from pydantic import BaseModel, Field


class ImprovedTitleOutput(BaseModel):
    """Output from title generation step."""

    improved_title: str = Field(
        description="A polished, professional course title that is clear, engaging, and accurately represents the content."
    )
    description: str = Field(
        description="A compelling 2-3 sentence description of the course that highlights what learners will gain."
    )


class CourseOutcomesOutput(BaseModel):
    """Output from outcomes generation step."""

    outcomes: str = Field(
        description="A formatted list of 3-5 learning outcomes as bullet points, each starting with an action verb."
    )


class SMEPersona(BaseModel):
    """A subject matter expert persona generated by the wizard."""

    id: str = Field(description="Unique identifier (e.g., 'sme-1', 'sme-2', 'sme-3')")
    job_title: str = Field(description="Professional job title")
    description: str = Field(
        description="2-3 sentence background describing their expertise"
    )
    skills: list[str] = Field(description="3-5 key skills")
    voice: str = Field(description="Their teaching voice/style")


class SMEPersonasOutput(BaseModel):
    """Output from SME persona generation step."""

    personas: list[SMEPersona] = Field(
        description="3 diverse SME personas with different expertise angles",
        min_length=3,
        max_length=3,
    )


class AudiencePersona(BaseModel):
    """A target audience persona generated by the wizard."""

    id: str = Field(description="Unique identifier")
    role: str = Field(description="Their current job role or profile label")
    description: str = Field(
        description="2-3 sentence description of their background and experience level"
    )
    goals: list[str] = Field(description="2-4 learning goals")


class AudiencePersonasOutput(BaseModel):
    """Output from audience persona generation step."""

    personas: list[AudiencePersona] = Field(
        description="3 diverse audience personas representing different learner profiles",
        min_length=3,
        max_length=3,
    )


class ToneOption(BaseModel):
    """A tone/style option generated by the wizard."""

    id: str = Field(description="Unique identifier")
    name: str = Field(description="Short name for this tone")
    description: str = Field(
        description="2-3 sentence description of the tone"
    )
    level_of_detail: str = Field(
        description="The depth of content coverage: 'brief', 'moderate', or 'comprehensive'"
    )


class ToneOptionsOutput(BaseModel):
    """Output from tone options generation step."""

    options: list[ToneOption] = Field(
        description="3 distinct tone/style options for the course",
        min_length=3,
        max_length=3,
    )
